<?php

declare(strict_types=1);

namespace Hirasso\HTMLObfuscator\Commands;

use League\CommonMark\Environment\Environment;
use League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension;
use League\CommonMark\Extension\HeadingPermalink\HeadingPermalinkExtension;
use League\CommonMark\MarkdownConverter;
use Spatie\CommonMarkShikiHighlighter\HighlightCodeExtension;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

use function Hirasso\HTMLObfuscator\obfuscate;

/** @codeCoverageIgnore */
#[AsCommand(name: 'readme:generate')]
class GenerateReadmeCommand extends Command
{
    protected function configure(): void
    {
        $this->setDescription('Generate demo/readme.generated.html from README.md');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $root = dirname(__DIR__, 2);
        $readmePath = "{$root}/README.md";
        $outputPath = "{$root}/demo/readme.generated.html";

        $markdown = file_get_contents($readmePath);
        if ($markdown === false) {
            $output->writeln("<error>Could not read {$readmePath}</error>");
            return Command::FAILURE;
        }

        // Extract only the part between <!-- demo-readme:start --> and <!-- demo-readme:end -->
        if (!preg_match('/<!--\s*demo-readme:start\s*-->(.*?)<!--\s*demo-readme:end\s*-->/s', $markdown, $matches)) {
            $output->writeln('<error>Could not find <!-- demo-readme:start/end --> markers in README.md</error>');
            return Command::FAILURE;
        }
        $markdown = trim($matches[1]);

        // Render > [!NOTE] as a styled blockquote
        $markdown = preg_replace('/^> \[!NOTE\]$/m', '> **Note:**', $markdown) ?? $markdown;

        $markdown = $this->prependRealDemoMarkdown($markdown);

        $environment = new Environment([
            'heading_permalink' => [
                'apply_id_to_heading' => true,
                'id_prefix' => '',
                'fragment_prefix' => '',
                'symbol' => '#',
                'insert' => 'after',
                'html_class' => 'anchor',
                'aria_hidden' => false,
            ],
        ]);
        $environment->addExtension(new CommonMarkCoreExtension());
        $environment->addExtension(new HighlightCodeExtension('rose-pine-moon'));
        $environment->addExtension(new HeadingPermalinkExtension());

        $converter = new MarkdownConverter($environment);
        $html = $converter->convert($markdown)->getContent();

        // Rewrite relative hrefs to absolute GitHub URLs
        $repoUrl = 'https://github.com/hirasso/html-obfuscator/tree/main';
        $html = preg_replace_callback(
            '/href="((?!https?:|#|mailto:|tel:|\/)[^"]+)"/',
            fn ($m) => sprintf('href="%s/%s"', $repoUrl, ltrim($m[1], './')),
            $html
        ) ?? $html;

        file_put_contents($outputPath, $this->trimLines(<<<HTML
            <!-- auto-generated by `composer generate-readme`. Do not edit directly -->
            $html
        HTML));

        $output->writeln("<info>Generated {$outputPath}</info>");

        return Command::SUCCESS;
    }

    /**
     * Prepend the demo to the markdown string
     */
    private function prependRealDemoMarkdown(string $markdown): string
    {
        $demo = (string) obfuscate(<<<HTML
            <p class="demo">Write me an email at <a href="mailto:mail@rassohilber.com">mail@rassohilber.com</a> or call me: <a href="tel:+4917620020805">+49 176 200 20 805</a>.</p>
        HTML)->injectClientScript(false);

        // $source = htmlspecialchars($demo);

        $prepended = $this->trimLines(<<<EOF
            ## Demo

            **There is NO visual difference between obfuscated and fully revealed state.**
            To see the effect, you must inspect one of the two links in the following paragraph,
            reload the page and then move your mouse or press any key:

            $demo

            **Crawlers that aren't able to simulate user interaction** will only ever see this:

            ```html
            $demo
            ```
        EOF);

        return "{$prepended}\n\n{$markdown}";
    }

    private function trimLines(string $text): string
    {
        return implode("\n", array_map('trim', preg_split("/\R/u", $text) ?: []));
    }
}
